version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.3.2
    container_name: elasticsearch7
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - "cluster.name=elasticsearch7"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - ELASTIC_PASSWORD=123456
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins/ik:/usr/share/elasticsearch/plugins/ik
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9210:9200
  kibana:
   container_name: kibana7
   hostname: kibana
   image: kibana:7.3.2
   restart: always
   volumes:
     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
   ports:
     - 5611:5601
   environment:
     - elasticsearch.hosts="http://elasticsearch:9200"
   depends_on:
     - elasticsearch
