cluster.name: elasticsearch-single
node.name: elasticsearch
network.bind_host: 0.0.0.0

#内存参数
indices.memory.index_buffer_size: 20%
#indices.memory.min_index_buffer_size: 64mb
#indices.memory.max_index_buffer_size: 256mb

bootstrap.memory_lock: false

xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
# 可选参数，可以设置 xpack 采集性能数据的索引范围，即仅对列表中的索引进行数据采集
# xpack.monitoring.collection.indices: logstash-*, index1, test2
# 可选参数，设置数据采集的周期，默认为 10 秒
# xpack.monitoring.collection.interval: 5

# logger.org.elasticsearch.transport: trace

# ------------------------------------------------------
# 从5.x 版本以后，慢查询日志只能设置在索引级别，无法设置全局的阈值
# ------------------------------------------------------
# # 记录获取慢日志
# index.search.slowlog.threshold.fetch.warn: 1s
# index.search.slowlog.threshold.fetch.info: 200ms
# index.search.slowlog.threshold.fetch.debug: 60ms
# index.search.slowlog.threshold.fetch.trace: 50ms
# # 记录查询慢日志
# index.search.slowlog.threshold.query.warn: 1s
# index.search.slowlog.threshold.query.debug: 500ms

# # 索引慢日志
# index.search.slowlog.threshold.index.warn: 10s
# index.search.slowlog.threshold.index.info: 5s
# index.search.slowlog.threshold.index.debug: 2s
# index.search.slowlog.threshold.index.trace: 500ms
# index.search.slowlog.level: trace
# index.search.slowlog.source: 1000

# ------------------------------------------------------
# 这个配置是 7.0 新加入的参数，如果使用低于 7.0 的版本需要注释掉
# ------------------------------------------------------
#cluster.initial_master_nodes: 172.27.14.194

# ------------------------------------------------------
# 测试发现 8.4.0 版本后这两个参数也不支持，暂时关闭
# ------------------------------------------------------
#node.master: true
#node.data: true

bootstrap.system_call_filter: false
